Add stringify method
bem-sdk/bem-import-notation pull request #11
Opened 2017-03-02 23:04 UTC by Yeti-or

fix #3

2017-03-02 23:15 UTC, Yeti-or commented
@zxqfox I didn't implement throwing on different blocks in array, or block + elem.
Are you sure that we need validation of input ?

2017-03-05 12:11 UTC, awinogradov commented on tests/stringify.js
> +        ])).to.eql('b:popup m:autoclosable=yes');
eql is the deep method

2017-03-09 18:35 UTC, Yeti-or commented on tests/stringify.js
> +        ])).to.eql('b:popup m:autoclosable=yes');
fixed

2017-03-09 19:00 UTC, zxqfox commented on index.js
> +    m : m => Object.keys(m).reduce((acc, name) => acc + `${tmpl.mn(name)}${tmpl.mv(m[name])}`, ''),
Давай `Object.keys(m).reduce(n => tmpl.mn(n) + tmpl.mv(m[n])).join('');`?

2017-03-09 19:11 UTC, qfox requested changes

2017-03-09 19:11 UTC, zxqfox commented on index.js
> +    const merged = [].concat(cells).reduce((acc, cell) => {
assertov dobavim?

2017-03-09 19:11 UTC, zxqfox commented on package.json
> +    "cover": "nyc mocha tests",
ну не делай так, test же стандарт

2017-03-10 18:16 UTC, zxqfox commented on README.md
> +`entities`| `array`  | Array of [BEM entities] to merge into bem-import string [notation](#notation)
into import string notation

2017-03-10 18:21 UTC, qfox reviewed
Po kodu vrode norm

2017-03-10 18:21 UTC, zxqfox commented on README.md
> +Forms a string from [bem entities]. Be aware to merge only one type of entities.
BEM entities

2017-03-10 18:21 UTC, zxqfox commented on README.md
> +Array must contain block and it's mods, or elem and it's mods.
modifiers

The array should contains one block or one elem and optionally it's modifiers.

2017-03-10 18:21 UTC, zxqfox commented on index.js
> + * @param {BemCell[]} - Array of bem-entites to merge into bem-import string notation
BEM entities

2017-03-10 18:21 UTC, zxqfox commented on index.js
> + * @param {BemCell[]} - Array of bem-entites to merge into bem-import string notation
import string notation

2017-03-10 18:21 UTC, zxqfox commented on index.js
> + * Get bem-import string notation representation of a bem-cells array.
Creates BEM import string notation of passed array with BemCell objects. ?

2017-03-10 18:21 UTC, zxqfox commented on index.js
> + * @param {BemCell[]} - Array of bem-entites to merge into bem-import string notation
Array → Set?

2017-03-10 18:41 UTC, merged